language: python
sudo: required
dist: xenial
python:
  - "3.7"
before_install:
  - 'cd backend/'
install:
  - 'pip install pipenv'
  - 'pipenv sync'
before_script:
  - 'cd backend/'
script:
  - 'cd backend/'
  - 'python manage.py test'