language: python
sudo: required
dist: xenial
python:
  - "3.7"
before_install:
  - 'cd backend/'
  - 'curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python'
install:
  - 'source $HOME/.poetry/env'
  - 'poetry install'
script:
  - 'poetry run python manage.py test'